<p style="font-size: 16px; color:blue;">
    Use the below shortcodes for the category data.<br/>
    <ul>
        <li>{name} => For category name.</li>
        <li>{url} => For category url.</li>
        <li>{generate_low_price_products_list} => This will generate html of 3 products list with lowest price.</li>
        <li>{generate_most_viewed_products_list} => This will generate html of 3 most viewed products list.</li>
    </ul>
</p>